import { Platform } from 'react-native';

export default {
  backgroundColor: '#5cb85c',
  textInputBgColor: 'black',
  pickerBgColor: 'transparent',
  textInputIconColor: '#000',
  pickerColorSelected: '#000',
  inputBorderColor: '#D9D5DC',
  borderWidth: 1,
  inputColorPlaceholder: '#ADADAD',
  inputColor: '#575757',
  inputActiveBgColor: '#5a5',
  inputActiveColor: '#333',
  inputFontSize: 15,
  labelActiveColor: '#575757',
  errorMsgColor: '#ed2f2f',
  changeTextInputColorOnError: true,
  textInputErrorIcon: 'close-circle',
  inputStyle: {
    borderBottomWidth: 0,
    alignSelf: 'flex-start',
  },
  inputContainerStyle: {
    justifyContent: 'center',
    alignSelf: 'stretch',
    borderRadius: 40,
    borderWidth: 1,
    borderColor: '#D9D5DC',
    height: 45,
    marginVertical: 10,
    paddingLeft: 15,
    overflow: 'hidden',
    backgroundColor: '#5cb85c',
  },
};
